/// everything below here is generated by my local Qwen3.5 with the following prompt:
///     I have the following C constants.h file can you give me a rust file that represents that as an enum and has functions to convert back and forth?
///     (all the INPUT_* const in commons.h)
/// I ain't typing that shit 🗿 (i did cross check it though)

/// Represents the input event types defined in the C constants.h file.
///
/// Uses `#[repr(u32)]` to ensure the integer values match the C macros exactly.
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u32)]
pub enum InputEvent {
    // X Buttons (Mouse/Touchpad Buttons)
    BtnXLeft = 0,
    BtnXHome = 1,
    BtnXRight = 2,

    // Touch Events
    TouchPress = 0x10,
    TouchRelease = 0x11,
    TouchUpdate = 0x12,

    // Pen Events
    PenPress = 0x20,
    PenRelease = 0x21,
    PenUpdate = 0x22,

    // General Buttons
    BtnPress = 0x30,
    BtnRelease = 0x31,

    // Virtual Keyboard (VKB) Press/Release
    VkbPress = 0x40,
    VkbRelease = 0x41,

    // Keyboard Modifiers/Keys
    VkbShiftMod = 0x100_000,
    VkbCtrlMod = 0x200_000,
    VkbAltMod = 0x400_000,
    VkbDel = 0x7f,
    VkbPgUp = 0x80,
    VkbPgDown = 0x81,
    VkbDown = 0x82,
    VkbUp = 0x83,
    VkbLeft = 0x84,
    VkbRight = 0x85,
    VkbHome = 0x86,
    VkbEnd = 0x87,
}

impl InputEvent {
    /// Converts a raw u32 integer value into an `InputEvent` enum variant.
    /// Returns `None` if the value is not a defined constant.
    pub fn from_u32(code: u32) -> Option<Self> {
        match code {
            // X Buttons
            0 => Some(Self::BtnXLeft),
            1 => Some(Self::BtnXHome),
            2 => Some(Self::BtnXRight),

            // Touch
            0x10 => Some(Self::TouchPress),
            0x11 => Some(Self::TouchRelease),
            0x12 => Some(Self::TouchUpdate),

            // Pen
            0x20 => Some(Self::PenPress),
            0x21 => Some(Self::PenRelease),
            0x22 => Some(Self::PenUpdate),

            // Buttons
            0x30 => Some(Self::BtnPress),
            0x31 => Some(Self::BtnRelease),

            // VKB Press/Release
            0x40 => Some(Self::VkbPress),
            0x41 => Some(Self::VkbRelease),

            // Modifiers/Keys
            0x100_000 => Some(Self::VkbShiftMod),
            0x200_000 => Some(Self::VkbCtrlMod),
            0x400_000 => Some(Self::VkbAltMod),
            0x7f => Some(Self::VkbDel),
            0x80 => Some(Self::VkbPgUp),
            0x81 => Some(Self::VkbPgDown),
            0x82 => Some(Self::VkbDown),
            0x83 => Some(Self::VkbUp),
            0x84 => Some(Self::VkbLeft),
            0x85 => Some(Self::VkbRight),
            0x86 => Some(Self::VkbHome),
            0x87 => Some(Self::VkbEnd),
            _ => None,
        }
    }

    /// Converts the enum variant back to its raw u32 integer value.
    /// Because of `#[repr(u32)]`, this is equivalent to `self as u32`.
    pub fn to_u32(self) -> u32 {
        self as u32
    }
}

// Implementation of standard traits for easier usage with `try_from`
impl TryFrom<u32> for InputEvent {
    type Error = ();

    fn try_from(code: u32) -> Result<Self, Self::Error> {
        Self::from_u32(code).ok_or(())
    }
}
