name: Build and upload releases

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: "eeems/remarkable-toolchain:latest-rmpp"
            release_arch: aarch64
          - image: "eeems/remarkable-toolchain:latest-rm1"
            release_arch: arm32

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    env:
      XOVI_REPO: ${{github.workspace}}/xovi-repo

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: git clone https://github.com/asivery/xovi.git "$XOVI_REPO"

      - name: Install RCC
        run: |
          apt-get update
          apt-get install -y qt6-base-dev
          ln -s /usr/lib/qt6/libexec/rcc /usr/local/bin/rcc

      - name: Build AppLoad
        run: |
          . /opt/codex/*/*/environment-setup-*

          ./make.sh
        working-directory: ./xovi

      - name: Build shims
        run: |
          . /opt/codex/*/*/environment-setup-*

          mkdir build
          cd build
          cmake ..
          make
        working-directory: ./shim

      - name: Create build artifact
        run: |
          mkdir -p result/shims
          cp xovi/appload.so result/
          cp shim/build/qtfb-shim.so shim/build/qtfb-shim-32bit.so result/shims/
          cd result

          tar -czf ../appload.tar.gz *

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: appload-${{ matrix.release_arch }}
          path: appload.tar.gz

  release:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --repo "${{ github.repository }}" \
            --title "${{ github.ref_name }}" \
            appload-aarch64.tar.gz#appload-aarch64/appload.tar.gz \
            appload-arm32.tar.gz#appload-arm32/appload.tar.gz
